// app init
export const APP_INIT_REQUEST = 'APP_INIT_REQUEST';
export const APP_INIT_SUCCESS = 'APP_INIT_SUCCESS';
export const APP_INIT_FAILURE = 'APP_INIT_FAILURE';

// current user
export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';

// team
export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAILURE = 'GET_TEAM_FAILURE';

// territories
export const GET_TERRITORIES_REQUEST = 'GET_TERRITORIES_REQUEST';
export const GET_TERRITORIES_SUCCESS = 'GET_TERRITORIES_SUCCESS';
export const GET_TERRITORIES_FAILURE = 'GET_TERRITORIES_FAILURE';

export const CREATE_TERRITORY_REQUEST = 'CREATE_TERRITORY_REQUEST';
export const CREATE_TERRITORY_SUCCESS = 'CREATE_TERRITORY_SUCCESS';
export const CREATE_TERRITORY_FAILURE = 'CREATE_TERRITORY_FAILURE';

export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';